name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"
      - name: "Setup JDK 16"
        uses: "actions/setup-java@v2"
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Clean Build"
        run: "./gradlew clean build"
